### ISSUE TITLE
Local Observable Service for Development

### ISSUE THREAD

**Issue by sei-dshepard** [cmu-sei/Polar#1]
As a developer, I want to have a simple, local Observable service that I can start up to do some work/testing,
so that I don't have to rely on external services for basic development tasks.

### Acceptance Criteria:
**Installation and Setup:**
The service can be easily installed and configured on local machines.
Clear documentation is provided for setup and usage.

**Functionality:**
The service supports basic Observable operations such as subscribing, publishing, and unsubscribing.
It allows the simulation of different scenarios for testing purposes.
Provides a straightforward API for integration with existing development environments.

**Performance:**
The service runs efficiently without consuming excessive system resources.
It can handle multiple concurrent operations without significant latency.

**Usability:**
The service includes a user-friendly interface or command-line tool for managing Observables.
Error messages and logs are clear and helpful for troubleshooting.

**Security:**
The service operates locally without sending data to external servers.
It includes basic security features to prevent unauthorized access.

**Scalability:**
The service can be easily scaled for more extensive testing scenarios if needed.
Supports both single and multi-threaded operations.

**Compatibility:**
The service is compatible with major operating systems (Windows, macOS, Linux).
It works seamlessly with popular development tools and frameworks.

**Maintenance:**
The service can be easily updated and maintained.
Includes automated testing to ensure reliability with new updates.

**Comment by daveman1010221** [comment]
The initial build of the Observable has been merged. I'm going to close this. Future work can be under a new issue.
