### ISSUE TITLE
Add an uninstaller to the setup scripts

### ISSUE THREAD

**Issue by sei-dshepard** [cmu-sei/Polar#6]
To improve the robustness of the installation process, we want to implement a "roll back" feature, which can also be the basis for a new uninstall script, for the base Polar stack and any installed agents. This is mostly expected to be used only in local development, but it's important for us to make the local development experience robust.

**Comment by sei-dshepard** [comment]
Also include issues identified during testing of the setup process. Please list the issues found here, so we can track them.

**Comment by vonjackets** [comment]
@rmdettmar updated the dev_stack.sh script to add cleanup, closing this issue retroactively.
